name: Pull Request Update

concurrency:
  group: pullrequest-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request_target:

jobs:
  test:
    uses: viam-modules/ams/.github/workflows/test.yml@main
    secrets:
      MONGODB_TEST_OUTPUT_URI: ${{ secrets.MONGODB_TEST_OUTPUT_URI }}
      DOCKER_PUBLIC_READONLY_PAT: ${{ secrets.DOCKER_PUBLIC_READONLY_PAT }}

  license_finder:
    uses: viam-modules/ams/.github/workflows/license_finder.yml@main
